# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

tasks:
  default:
    silent: true
    cmds:
      - task --list --color

  venv:
    desc: Create Poetry environment
    preconditions:
      - test -f $(which poetry)
    cmds:
      - poetry env use python3.12
      - poetry install --no-root
    run: once
    internal: true

  run:
    desc: Run Django server
    preconditions:
      - test -f $(which poetry)
    dir: src
    deps:
      - venv
    cmds:
      - poetry run python manage.py runserver
    dotenv:
      - .env

  migrate:make:
    desc: Generate migrations
    preconditions:
      - test -f $(which poetry)
    dir: src
    deps:
      - venv
    cmds:
      - poetry run python manage.py makemigrations
    dotenv:
      - .env

  migrate:apply:
    desc: Apply migrations
    preconditions:
      - test -f $(which poetry)
    dir: src
    deps:
      - venv
      - migrate:make
    cmds:
      - poetry run python manage.py migrate
    dotenv:
      - .env

  dc:up:
    desc: Run docker compose up
    preconditions:
      - test -f $(which docker)
    cmds:
      - docker compose up -d --build
    dotenv:
      - .env

  dc:down:
    desc: Run docker compose down
    preconditions:
      - test -f $(which docker)
    cmds:
      - docker compose down
